## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)

## ----load-packages, message=FALSE, warning=FALSE, eval=FALSE------------------
# # install if not have
# # install.packages("devtools")
# 
# # Install DIVAS package from GitHub
# # devtools::install_github("ByronSyun/DIVAS_Develop", ref = "DIVAS-v1")
# 
# # Or install from local folder
# # devtools::load_all("DIVAS-main")
# 
# # Install a current 1.x CVXR release (example shown with 1.0-15)
# # remotes::install_version("CVXR", version = "1.0-15", repos = "https://cloud.r-project.org")
# 
# # For pkgdown, libraries are generally not needed here if the package is loaded,
# # # library(R.matlab)
# # # library(qs)
# # # library(DIVAS)

## ----load-data, eval=FALSE----------------------------------------------------
# # library(R.matlab)
# # library(qs)
# # Assuming 'toyDataThreeWay.mat' is in your working directory or provide the full path
# # data <- readMat('toyDataThreeWay.mat')
# # str(data$datablock)

## ----prepare-data, eval=FALSE-------------------------------------------------
# # datablock_list <- list(
# #   Block1 = data$datablock[1,1][[1]][[1]],
# #   Block2 = data$datablock[1,2][[1]][[1]],
# #   Block3 = data$datablock[1,3][[1]][[1]]
# # )
# #
# # print(paste("Block 1 dimensions:", dim(datablock_list[[1]])))
# # print(paste("Block 2 dimensions:", dim(datablock_list[[2]])))
# # print(paste("Block 3 dimensions:", dim(datablock_list[[3]])))

## ----run-divas, eval=FALSE----------------------------------------------------
# # Run the main DIVAS function
# # Use default parameters for this example
# # divas_results <- DIVASmain(datablock_list)
# #
# # # The result is a list containing various outputs
# # names(divas_results)

## ----loading-plot-example, eval=FALSE-----------------------------------------
# # These plots are generated by the DJIVEAngleDiagnosticJP function
# # plots <- DJIVEAngleDiagnosticJP(datablock_list, dataname, divas_results,
# #                               randseed = 566, titlestr = "Demo")

## ----score-plot-example, eval=FALSE-------------------------------------------
# # print(plots$score)

## ----examine-basis, eval=FALSE------------------------------------------------
# # names(divas_results$jointBasisMap)
# # dim(divas_results$jointBasisMap[["7"]])

## ----examine-loadings, eval=FALSE---------------------------------------------
# # str(divas_results$matLoadings, max.level = 2)

## ----load-qs, eval=FALSE------------------------------------------------------
# # install.packages("qs")
# # library(qs)

## ----gnp-example, eval=FALSE--------------------------------------------------
# # gnp <- qread("gnp_imputed.qs")
# #
# # datablock <- gnp$datablock
# # divasRes <- DIVASmain(datablock, nsim = 400, colCent = TRUE)
# #
# # # Create names for the data blocks
# # dataname <- paste0("DataBlock_", 1:length(datablock))
# # plots <- DJIVEAngleDiagnosticJP(datablock, dataname, divasRes, 566, "GNP Demo")
